version: '3'
services:
  api:
    image: api:ralali
    container_name: api-ralali
    build:
      context: ./
      dockerfile: api.Dockerfile
      target: runner
    restart: always
    ports:
      - "8081:8081"
    networks:
      - local-network-ralali
      
  mysql_db_ralali:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=ralali
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_TCP_PORT=52000
    ports:
      - '52000:52000'
    networks:
      - local-network-ralali

networks:
  local-network-ralali:
    driver: bridge